/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;

import ProceduresJDBC.CreationSeminaire;
import ProceduresJDBC.EditerAll;
import ProceduresJDBC.OuvertureInscription;
import java.awt.Color;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import models.Animateur;
import models.InscriptionSeminaire;
import models.Participant;
import models.Seminaire;

/**
 *
 * @author hpp
 */
public class FormInscription extends javax.swing.JFrame {
    EditerAll e = new EditerAll();
    /**
     * Creates new form SignIn
     */
    public FormInscription() throws ParseException, SQLException {
        initComponents();
        EditerAll e = new EditerAll();
        for (Seminaire sem : e.editerSeminaire()) {
            cmbInscriptionSem.addItem(String.valueOf(sem.getId()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblInscriptionNom = new javax.swing.JLabel();
        lblInscriptionPrenom = new javax.swing.JLabel();
        lblInscriptionTel = new javax.swing.JLabel();
        lblInscriptionAdr = new javax.swing.JLabel();
        txtInscriptionTel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblInscriptionEmail = new javax.swing.JLabel();
        txtInscriptionPrenom = new javax.swing.JTextField();
        txtInscriptionNom = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btInscriptionSignup = new javax.swing.JButton();
        txtInscriptionEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInscriptionAdr = new javax.swing.JTextArea();
        chxInscriptionInfo = new javax.swing.JCheckBox();
        cmbInscriptionSem = new javax.swing.JComboBox<>();
        lblInscriptionSeminaire = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        datePickerInscription = new org.jdesktop.swingx.JXDatePicker();
        lblInscriptionDate = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));

        jPanel4.setBackground(new java.awt.Color(45, 118, 232));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Home_50px_2.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel16MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Add_User_Male_40px.png"))); // NOI18N
        jLabel14.setText(" Inscription");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Login_30px_1.png"))); // NOI18N
        jLabel1.setText("Sign In");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(2, 2, 2)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblInscriptionNom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblInscriptionNom.setForeground(new java.awt.Color(51, 51, 51));
        lblInscriptionNom.setText("Nom :");

        lblInscriptionPrenom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblInscriptionPrenom.setForeground(new java.awt.Color(51, 51, 51));
        lblInscriptionPrenom.setText("Prénom :");

        lblInscriptionTel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblInscriptionTel.setForeground(new java.awt.Color(51, 51, 51));
        lblInscriptionTel.setText("Téléphone :");

        lblInscriptionAdr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblInscriptionAdr.setForeground(new java.awt.Color(51, 51, 51));
        lblInscriptionAdr.setText("Adresse :");

        txtInscriptionTel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtInscriptionTel.setForeground(new java.awt.Color(51, 51, 51));
        txtInscriptionTel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Phone_30px.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Name_30px.png"))); // NOI18N

        lblInscriptionEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblInscriptionEmail.setForeground(new java.awt.Color(51, 51, 51));
        lblInscriptionEmail.setText("E-mail :");

        txtInscriptionPrenom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtInscriptionPrenom.setForeground(new java.awt.Color(51, 51, 51));
        txtInscriptionPrenom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        txtInscriptionNom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtInscriptionNom.setForeground(new java.awt.Color(51, 51, 51));
        txtInscriptionNom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Email_30px.png"))); // NOI18N

        btInscriptionSignup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btInscriptionSignup.setForeground(new java.awt.Color(51, 51, 51));
        btInscriptionSignup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Ok_30px.png"))); // NOI18N
        btInscriptionSignup.setText("Sign Up");
        btInscriptionSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btInscriptionSignupMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btInscriptionSignupMousePressed(evt);
            }
        });
        btInscriptionSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInscriptionSignupActionPerformed(evt);
            }
        });

        txtInscriptionEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtInscriptionEmail.setForeground(new java.awt.Color(51, 51, 51));
        txtInscriptionEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Home_Address_30px.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Name_30px.png"))); // NOI18N

        txtInscriptionAdr.setColumns(20);
        txtInscriptionAdr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtInscriptionAdr.setRows(5);
        jScrollPane1.setViewportView(txtInscriptionAdr);

        chxInscriptionInfo.setText("Je souhaite qu'on m'informe des nouveautés, seminaires de formation ");

        cmbInscriptionSem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choisir un seminaire" }));

        lblInscriptionSeminaire.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblInscriptionSeminaire.setForeground(new java.awt.Color(51, 51, 51));
        lblInscriptionSeminaire.setText("Seminaire :");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Checked_Checkbox_30px.png"))); // NOI18N

        lblInscriptionDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblInscriptionDate.setForeground(new java.awt.Color(51, 51, 51));
        lblInscriptionDate.setText("Date :");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Date_To_30px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblInscriptionPrenom, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblInscriptionNom, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblInscriptionSeminaire, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblInscriptionDate, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblInscriptionTel)
                                .addGap(18, 18, 18))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(lblInscriptionEmail))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblInscriptionAdr)))
                        .addGap(23, 23, 23)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(chxInscriptionInfo)
                        .addContainerGap(125, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbInscriptionSem, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtInscriptionEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInscriptionTel)
                            .addComponent(txtInscriptionPrenom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInscriptionNom)
                            .addComponent(jScrollPane1)
                            .addComponent(datePickerInscription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(48, 48, 48))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btInscriptionSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtInscriptionNom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInscriptionNom)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtInscriptionPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblInscriptionPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtInscriptionTel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInscriptionTel)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(txtInscriptionEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInscriptionEmail))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblInscriptionSeminaire)
                            .addComponent(cmbInscriptionSem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(datePickerInscription, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblInscriptionDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInscriptionAdr)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chxInscriptionInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btInscriptionSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(45, 118, 232));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Add_User_Male_96px.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("AFRISEM Gestion Seminaire");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel13))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel12)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(1047, 683));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        // setLabelColor(jPanel4);
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        // resetLabelColor(jPanel4);
    }//GEN-LAST:event_jPanel4MouseExited

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        new FormSignIn().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jLabel1MousePressed

    private void btInscriptionSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInscriptionSignupActionPerformed
        String nomPart= (String) txtInscriptionNom.getText();
        String prenomPart= (String)  txtInscriptionPrenom.getText();
        int telPart = Integer.parseInt(txtInscriptionTel.getText());
        String emailPart= (String) txtInscriptionEmail.getText();
        String adrPart= (String) txtInscriptionAdr.getText();
        int idsem = Integer.parseInt((String)cmbInscriptionSem.getSelectedItem());
        Date dateIns=datePickerInscription.getDate();
        Participant partcip=new Participant(WIDTH, nomPart, prenomPart, adrPart, telPart, emailPart);
        OuvertureInscription inscrip = null;
        try {
            inscrip = new OuvertureInscription();
        } catch (ParseException ex) {
            Logger.getLogger(FormInscription.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            int idpart=inscrip.creerParticipant(partcip);
            int nbrPlaceMax = e.nbrPlaceMaxSeminaire(idsem);
            int nbrReserver = e.nbrPlaceMaxReserverSeminaire(idsem);
            OuvertureInscription inscSem =new OuvertureInscription();
            if(nbrReserver < nbrPlaceMax){
              InscriptionSeminaire inscription=new InscriptionSeminaire(idpart, idsem, dateIns, "confirme");
               System.out.println(" ok "+inscription.getIdParticipant()+" "+inscription.getIdSeminaire()+" "+inscription.getDate()+" "+inscription.getEtat());
               inscSem.Inscription(inscription);
            }else{
              InscriptionSeminaire inscription=new InscriptionSeminaire(idpart, idsem, dateIns, "attente");
              System.out.println(" ok "+inscription.getIdParticipant()+" "+inscription.getIdSeminaire()+" "+inscription.getDate()+" "+inscription.getEtat());
              inscSem.Inscription(inscription);
            }  
        
        } catch (SQLException ex) {
            Logger.getLogger(FormInscription.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(FormInscription.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        if(chxInscriptionInfo.isSelected()){
            JOptionPane jop1;
            jop1 = new JOptionPane();
            jop1.showMessageDialog(null, "Merci de votre inscription", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btInscriptionSignupActionPerformed

    private void jLabel16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MousePressed
        new FormMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel16MousePressed

    private void btInscriptionSignupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btInscriptionSignupMousePressed
         new FormMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btInscriptionSignupMousePressed

    private void btInscriptionSignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btInscriptionSignupMouseEntered
       
    }//GEN-LAST:event_btInscriptionSignupMouseEntered
    private void setColor(JPanel panel) {
        panel.setBackground(new Color(197, 197, 197));
    }

    private void resetColor(JPanel panel) {
        panel.setBackground(new Color(240, 240, 240));
    }

    private void resetLabelColor(JLabel label) {
        label.setBackground(new Color(45, 118, 232));
    }

    private void setLabelColor(JLabel label) {
        label.setBackground(new Color(197, 197, 197));
    }

    private void resetJPanelColor(JPanel panel) {
        panel.setBackground(new Color(45, 118, 232));
    }

    private void setJPanelColor(JPanel panel) {
        panel.setBackground(new Color(197, 197, 197));
    }

    private void setTextColor(JTextField textField) {
        textField.setBackground(new Color(240, 240, 240));
    }

    private void resetTextColor(JTextField textField) {
        textField.setBackground(new Color(45, 118, 232));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormInscription().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(FormInscription.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(FormInscription.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btInscriptionSignup;
    private javax.swing.JCheckBox chxInscriptionInfo;
    private javax.swing.JComboBox<String> cmbInscriptionSem;
    private org.jdesktop.swingx.JXDatePicker datePickerInscription;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInscriptionAdr;
    private javax.swing.JLabel lblInscriptionDate;
    private javax.swing.JLabel lblInscriptionEmail;
    private javax.swing.JLabel lblInscriptionNom;
    private javax.swing.JLabel lblInscriptionPrenom;
    private javax.swing.JLabel lblInscriptionSeminaire;
    private javax.swing.JLabel lblInscriptionTel;
    private javax.swing.JTextArea txtInscriptionAdr;
    private javax.swing.JTextField txtInscriptionEmail;
    private javax.swing.JTextField txtInscriptionNom;
    private javax.swing.JTextField txtInscriptionPrenom;
    private javax.swing.JTextField txtInscriptionTel;
    // End of variables declaration//GEN-END:variables
}
