/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;

import ProceduresJDBC.CreationSeminaire;
import ProceduresJDBC.EditerAll;
import java.awt.Color;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import models.Animateur;
import models.Conference;
import models.Conferencier;
import models.DefaultTableModeleAll;
import models.Prestataire;
import models.Seminaire;

/**
 *
 * @author hpp
 */
public class FormConference extends javax.swing.JFrame {
 DefaultTableModeleAll tab=new DefaultTableModeleAll();
  EditerAll e = new EditerAll();
    /**
     * Creates new form Home
     * @throws java.text.ParseException
     * @throws java.sql.SQLException
     */
    public FormConference() throws ParseException, SQLException {
        initComponents();
        for (Conferencier conferencier : e.editerConferencier()) {
            cmbConferenceIdConf.addItem(String.valueOf(conferencier.getId()));
        }
        for (Seminaire sem : e.editerSeminaire()) {
            cmbConferenceIdSem.addItem(String.valueOf(sem.getId()));
        }
        tabConference.setModel(tab.tableModelConference());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblConferenceIdSem = new javax.swing.JLabel();
        lblConferenceIdConf = new javax.swing.JLabel();
        lblConferenceTitreConf = new javax.swing.JLabel();
        cmbConferenceIdSem = new javax.swing.JComboBox<>();
        lblConferenceSupport = new javax.swing.JLabel();
        lblConferenceMontantPrest = new javax.swing.JLabel();
        txtConferenceMontantPres = new javax.swing.JTextField();
        lblConferenceActivites = new javax.swing.JLabel();
        txtConferenceTitreConf = new javax.swing.JTextField();
        btConferenceCreate = new javax.swing.JButton();
        btConferenceDelete = new javax.swing.JButton();
        btConferenceUpdate = new javax.swing.JButton();
        btConferenceCancel = new javax.swing.JButton();
        txtConferenceActivites = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cmbConferenceIdConf = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        txtConferenceSupport = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabConference = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));

        jPanel4.setBackground(new java.awt.Color(45, 118, 232));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Conference_30px_1.png"))); // NOI18N
        jLabel14.setText(" Conférence");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Logout_Rounded_Left_30px.png"))); // NOI18N
        jLabel1.setText("Sign Out");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(45, 118, 232));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Home_50px_2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(508, 508, 508)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblConferenceIdSem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblConferenceIdSem.setForeground(new java.awt.Color(51, 51, 51));
        lblConferenceIdSem.setText("ID Seminaire :");

        lblConferenceIdConf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblConferenceIdConf.setForeground(new java.awt.Color(51, 51, 51));
        lblConferenceIdConf.setText("ID Conferencier :");

        lblConferenceTitreConf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblConferenceTitreConf.setForeground(new java.awt.Color(51, 51, 51));
        lblConferenceTitreConf.setText("Titre Conférence :");

        cmbConferenceIdSem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbConferenceIdSem.setForeground(new java.awt.Color(51, 51, 51));
        cmbConferenceIdSem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectionnez Seminaire" }));
        cmbConferenceIdSem.setToolTipText("");
        cmbConferenceIdSem.setBorder(null);
        cmbConferenceIdSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbConferenceIdSemActionPerformed(evt);
            }
        });

        lblConferenceSupport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblConferenceSupport.setForeground(new java.awt.Color(51, 51, 51));
        lblConferenceSupport.setText("Support :");

        lblConferenceMontantPrest.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblConferenceMontantPrest.setForeground(new java.awt.Color(51, 51, 51));
        lblConferenceMontantPrest.setText("Montant Prestation :");

        txtConferenceMontantPres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtConferenceMontantPres.setForeground(new java.awt.Color(51, 51, 51));
        txtConferenceMontantPres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        lblConferenceActivites.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblConferenceActivites.setForeground(new java.awt.Color(51, 51, 51));
        lblConferenceActivites.setText("Activités :");

        txtConferenceTitreConf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtConferenceTitreConf.setForeground(new java.awt.Color(51, 51, 51));
        txtConferenceTitreConf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        btConferenceCreate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btConferenceCreate.setForeground(new java.awt.Color(51, 51, 51));
        btConferenceCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Ok_30px.png"))); // NOI18N
        btConferenceCreate.setText("Create");
        btConferenceCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConferenceCreateActionPerformed(evt);
            }
        });

        btConferenceDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btConferenceDelete.setForeground(new java.awt.Color(51, 51, 51));
        btConferenceDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Trash_30px.png"))); // NOI18N
        btConferenceDelete.setText("Delete");
        btConferenceDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConferenceDeleteActionPerformed(evt);
            }
        });

        btConferenceUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btConferenceUpdate.setForeground(new java.awt.Color(51, 51, 51));
        btConferenceUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Edit_30px.png"))); // NOI18N
        btConferenceUpdate.setText("Update");
        btConferenceUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConferenceUpdateActionPerformed(evt);
            }
        });

        btConferenceCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btConferenceCancel.setForeground(new java.awt.Color(51, 51, 51));
        btConferenceCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Cancel_30px.png"))); // NOI18N
        btConferenceCancel.setText("Cancel");
        btConferenceCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConferenceCancelActionPerformed(evt);
            }
        });

        txtConferenceActivites.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtConferenceActivites.setForeground(new java.awt.Color(51, 51, 51));
        txtConferenceActivites.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Book_30px.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Activity_History_30px.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_ID_Verified_30px.png"))); // NOI18N

        cmbConferenceIdConf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbConferenceIdConf.setForeground(new java.awt.Color(51, 51, 51));
        cmbConferenceIdConf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectionnez Conferencier" }));
        cmbConferenceIdConf.setBorder(null);
        cmbConferenceIdConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbConferenceIdConfActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_ID_Verified_30px.png"))); // NOI18N

        txtConferenceSupport.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtConferenceSupport.setForeground(new java.awt.Color(51, 51, 51));
        txtConferenceSupport.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Header_1_30px.png"))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Bank_Euro_30px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(btConferenceCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btConferenceUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btConferenceDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btConferenceCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblConferenceIdSem)
                            .addComponent(lblConferenceIdConf)
                            .addComponent(lblConferenceTitreConf))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(cmbConferenceIdSem, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtConferenceTitreConf, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbConferenceIdConf, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblConferenceActivites))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblConferenceSupport))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(35, 35, 35)
                                .addComponent(lblConferenceMontantPrest)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtConferenceActivites, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtConferenceMontantPres, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel19))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtConferenceSupport, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblConferenceIdSem)
                                    .addComponent(cmbConferenceIdSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblConferenceSupport)
                                        .addComponent(txtConferenceSupport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel12))
                                .addGap(17, 17, 17)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblConferenceIdConf)
                                .addComponent(lblConferenceMontantPrest)
                                .addComponent(cmbConferenceIdConf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtConferenceMontantPres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel17)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblConferenceTitreConf)
                                    .addComponent(txtConferenceTitreConf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblConferenceActivites)
                                .addComponent(txtConferenceActivites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConferenceCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConferenceUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConferenceDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConferenceCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        tabConference.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Conferencier", "ID Seminaire", "Titre Conférence", "Support", "Montant Prestation", "Activités"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabConference);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1174, 713));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
       // setLabelColor(jPanel4);
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
       // resetLabelColor(jPanel4);
    }//GEN-LAST:event_jPanel4MouseExited

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        new FormMenu().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jLabel1MousePressed

    private void cmbConferenceIdSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbConferenceIdSemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbConferenceIdSemActionPerformed

    private void btConferenceDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConferenceDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btConferenceDeleteActionPerformed

    private void btConferenceUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConferenceUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btConferenceUpdateActionPerformed

    private void btConferenceCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConferenceCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btConferenceCancelActionPerformed

    private void cmbConferenceIdConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbConferenceIdConfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbConferenceIdConfActionPerformed

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        setJPanelColor(jPanel4);
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        resetJPanelColor(jPanel4);
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        new FormMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jPanel5MousePressed

    private void btConferenceCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConferenceCreateActionPerformed
        int idConf= Integer.parseInt((String) cmbConferenceIdConf.getSelectedItem());
        int idSem= Integer.parseInt((String) cmbConferenceIdSem.getSelectedItem());
        String titreConf = (String)txtConferenceTitreConf.getText();
        String supportConf= (String) txtConferenceSupport.getText();
        double montantPrest=Double.parseDouble(txtConferenceMontantPres.getText());
        String activites= (String) txtConferenceActivites.getText();
        Conference confer=new Conference(idConf, idSem, titreConf, supportConf, montantPrest, activites);
     try {
         CreationSeminaire sem=new CreationSeminaire();
         sem.creerConference(confer);
         tabConference.setModel(tab.tableModelConference());
     } catch (ParseException | SQLException ex) {
         Logger.getLogger(FormConference.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_btConferenceCreateActionPerformed
   private void setColor(JPanel panel){
         panel.setBackground(new Color(197,197,197));
    }
    private void resetColor(JPanel panel){
        panel.setBackground(new Color(240,240,240));
    }
    private void resetLabelColor(JLabel label){
         label.setBackground(new Color(45,118,232));
    }
     private void setLabelColor(JLabel label){
         label.setBackground(new Color(197,197,197));
    }
      private void resetJPanelColor(JPanel panel){
         panel.setBackground(new Color(45,118,232));
    }
     private void setJPanelColor(JPanel panel){
         panel.setBackground(new Color(197,197,197));
    }
     private void setTextColor(JTextField textField){
         textField.setBackground(new Color(240,240,240));
    }
      private void resetTextColor(JTextField textField){
         textField.setBackground(new Color(45,118,232));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormConference.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormConference.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormConference.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormConference.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormConference().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(FormConference.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(FormConference.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConferenceCancel;
    private javax.swing.JButton btConferenceCreate;
    private javax.swing.JButton btConferenceDelete;
    private javax.swing.JButton btConferenceUpdate;
    private javax.swing.JComboBox<String> cmbConferenceIdConf;
    private javax.swing.JComboBox<String> cmbConferenceIdSem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConferenceActivites;
    private javax.swing.JLabel lblConferenceIdConf;
    private javax.swing.JLabel lblConferenceIdSem;
    private javax.swing.JLabel lblConferenceMontantPrest;
    private javax.swing.JLabel lblConferenceSupport;
    private javax.swing.JLabel lblConferenceTitreConf;
    private javax.swing.JTable tabConference;
    private javax.swing.JTextField txtConferenceActivites;
    private javax.swing.JTextField txtConferenceMontantPres;
    private javax.swing.JTextField txtConferenceSupport;
    private javax.swing.JTextField txtConferenceTitreConf;
    // End of variables declaration//GEN-END:variables
}
