/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;

import ProceduresJDBC.CreationSeminaire;
import ProceduresJDBC.EditerAll;
import java.awt.Color;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import models.Animateur;
import models.Conferencier;
import models.DefaultTableModeleAll;
import models.Prestataire;
import models.Salle;
import models.Seminaire;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author hpp
 */
public class FormSeminaire extends javax.swing.JFrame {
 DefaultTableModeleAll tab=new DefaultTableModeleAll();
  EditerAll e = new EditerAll();
    /**
     * Creates new form Seminaire
     * @throws java.sql.SQLException
     * @throws java.text.ParseException
     */
 @SuppressWarnings("empty-statement")
    public FormSeminaire() throws SQLException, ParseException {
        initComponents();
        for (Prestataire prest : e.editerPrestataire()) {
            cmbSemPresta.addItem(String.valueOf(prest.getId()));
        }
        for (Animateur anim : e.editerAnimateur()) {
            cmbSemAnim.addItem(String.valueOf(anim.getId()));
        }
        String [] listeDuree = {"MATIN","APRES-MIDI","JOURNEE"};
        for(String dure : listeDuree){
            CmbSemDuréeSem.addItem(dure);
        }
        tabSeminaire.setModel(tab.tableModelSeminaire());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblSemIdAnim = new javax.swing.JLabel();
        CmbSemDuréeSem = new javax.swing.JComboBox<>();
        lblSemIdPresta = new javax.swing.JLabel();
        lblSemNumSalle = new javax.swing.JLabel();
        lblSemThemeSem = new javax.swing.JLabel();
        cmbSemAnim = new javax.swing.JComboBox<>();
        lblSemNbPlace = new javax.swing.JLabel();
        lblSemTarifPers = new javax.swing.JLabel();
        lblSemDateSem = new javax.swing.JLabel();
        dPickerSeminaire = new org.jdesktop.swingx.JXDatePicker();
        txtSemNbPlace = new javax.swing.JTextField();
        txtSemTarifPers = new javax.swing.JTextField();
        lblSemDureeSem = new javax.swing.JLabel();
        cmbSemPresta = new javax.swing.JComboBox<>();
        txtSemThemeSem = new javax.swing.JTextField();
        btSemCreat = new javax.swing.JButton();
        btSemDelete = new javax.swing.JButton();
        btSemUpdate = new javax.swing.JButton();
        btSemCancel = new javax.swing.JButton();
        cmbSemSalle = new javax.swing.JComboBox<>();
        lblSemDepenseMin = new javax.swing.JLabel();
        lblSemRecetteMax = new javax.swing.JLabel();
        lblSemRecetteMin = new javax.swing.JLabel();
        lblSemDepenseMax = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabSeminaire = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));

        jPanel4.setBackground(new java.awt.Color(45, 118, 232));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Home_50px_2.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel16MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Conference_40px.png"))); // NOI18N
        jLabel14.setText(" Seminaire");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Logout_Rounded_Left_30px.png"))); // NOI18N
        jLabel1.setText("Sign Out");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Notification_30px_1.png"))); // NOI18N
        jLabel10.setText("1");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 596, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 39, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblSemIdAnim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSemIdAnim.setForeground(new java.awt.Color(51, 51, 51));
        lblSemIdAnim.setText("ID Animateur :");

        CmbSemDuréeSem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CmbSemDuréeSem.setForeground(new java.awt.Color(51, 51, 51));
        CmbSemDuréeSem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choisir la durée" }));
        CmbSemDuréeSem.setBorder(null);
        CmbSemDuréeSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbSemDuréeSemActionPerformed(evt);
            }
        });

        lblSemIdPresta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSemIdPresta.setForeground(new java.awt.Color(51, 51, 51));
        lblSemIdPresta.setText("ID Prestataire :");

        lblSemNumSalle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSemNumSalle.setForeground(new java.awt.Color(51, 51, 51));
        lblSemNumSalle.setText("N° Salle :");

        lblSemThemeSem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSemThemeSem.setForeground(new java.awt.Color(51, 51, 51));
        lblSemThemeSem.setText("Theme Seminaire : ");

        cmbSemAnim.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbSemAnim.setForeground(new java.awt.Color(51, 51, 51));
        cmbSemAnim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectionnez un Animateur" }));
        cmbSemAnim.setBorder(null);
        cmbSemAnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSemAnimActionPerformed(evt);
            }
        });

        lblSemNbPlace.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSemNbPlace.setForeground(new java.awt.Color(51, 51, 51));
        lblSemNbPlace.setText("  Nombre de Place :");

        lblSemTarifPers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSemTarifPers.setForeground(new java.awt.Color(51, 51, 51));
        lblSemTarifPers.setText(" Tarif/Personne :");

        lblSemDateSem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSemDateSem.setForeground(new java.awt.Color(51, 51, 51));
        lblSemDateSem.setText("Date :");

        txtSemNbPlace.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSemNbPlace.setForeground(new java.awt.Color(51, 51, 51));
        txtSemNbPlace.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        txtSemTarifPers.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSemTarifPers.setForeground(new java.awt.Color(51, 51, 51));
        txtSemTarifPers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        lblSemDureeSem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSemDureeSem.setForeground(new java.awt.Color(51, 51, 51));
        lblSemDureeSem.setText(" Durée Seminaire :");

        cmbSemPresta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbSemPresta.setForeground(new java.awt.Color(51, 51, 51));
        cmbSemPresta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectionnez Prestataire" }));
        cmbSemPresta.setBorder(null);
        cmbSemPresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSemPrestaActionPerformed(evt);
            }
        });

        txtSemThemeSem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSemThemeSem.setForeground(new java.awt.Color(51, 51, 51));
        txtSemThemeSem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        btSemCreat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSemCreat.setForeground(new java.awt.Color(51, 51, 51));
        btSemCreat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Ok_30px.png"))); // NOI18N
        btSemCreat.setText("Create");
        btSemCreat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSemCreatActionPerformed(evt);
            }
        });

        btSemDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSemDelete.setForeground(new java.awt.Color(51, 51, 51));
        btSemDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Trash_30px.png"))); // NOI18N
        btSemDelete.setText("Delete");
        btSemDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSemDeleteActionPerformed(evt);
            }
        });

        btSemUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSemUpdate.setForeground(new java.awt.Color(51, 51, 51));
        btSemUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Edit_30px.png"))); // NOI18N
        btSemUpdate.setText("Update");
        btSemUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSemUpdateActionPerformed(evt);
            }
        });

        btSemCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSemCancel.setForeground(new java.awt.Color(51, 51, 51));
        btSemCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Cancel_30px.png"))); // NOI18N
        btSemCancel.setText("Cancel");
        btSemCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSemCancelActionPerformed(evt);
            }
        });

        cmbSemSalle.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbSemSalle.setForeground(new java.awt.Color(51, 51, 51));
        cmbSemSalle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectionnez Salle" }));
        cmbSemSalle.setBorder(null);
        cmbSemSalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSemSalleActionPerformed(evt);
            }
        });

        lblSemDepenseMin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSemDepenseMin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        lblSemRecetteMax.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSemRecetteMax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        lblSemRecetteMin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSemRecetteMin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        lblSemDepenseMax.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSemDepenseMax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblSemNumSalle)
                                            .addComponent(lblSemIdPresta)
                                            .addComponent(lblSemDateSem))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dPickerSeminaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbSemPresta, 0, 355, Short.MAX_VALUE)
                                            .addComponent(cmbSemSalle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(lblSemIdAnim)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbSemAnim, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblSemTarifPers, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblSemDureeSem, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblSemNbPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(lblSemThemeSem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btSemCreat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btSemUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btSemDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btSemCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSemNbPlace)
                            .addComponent(txtSemTarifPers)
                            .addComponent(CmbSemDuréeSem, 0, 401, Short.MAX_VALUE)
                            .addComponent(txtSemThemeSem)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblSemDepenseMin, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSemDepenseMax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblSemRecetteMin, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSemRecetteMax, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSemNbPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSemNbPlace)
                    .addComponent(cmbSemAnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSemIdAnim))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSemIdPresta)
                    .addComponent(lblSemTarifPers)
                    .addComponent(txtSemTarifPers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSemPresta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSemNumSalle)
                        .addComponent(lblSemDureeSem)
                        .addComponent(cmbSemSalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CmbSemDuréeSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSemDateSem)
                            .addComponent(dPickerSeminaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSemThemeSem)
                            .addComponent(txtSemThemeSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btSemCreat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btSemUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btSemDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btSemCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSemDepenseMin, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSemDepenseMax, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSemRecetteMin, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSemRecetteMax, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        tabSeminaire.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Seminaire", "ID Prestataire", "ID Animateur", "N° Salle", "Theme ", "Nombre Place", "Tarif/Personne", "Date", "Durée"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabSeminaire);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1114, 704));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
         setJPanelColor(jPanel4);
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        resetJPanelColor(jPanel4);
    }//GEN-LAST:event_jPanel4MouseExited

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        new FormMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel1MousePressed

    private void CmbSemDuréeSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbSemDuréeSemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbSemDuréeSemActionPerformed

    private void cmbSemAnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSemAnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSemAnimActionPerformed

    private void cmbSemPrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSemPrestaActionPerformed
        int idPrestataire = Integer.parseInt((String)cmbSemPresta.getSelectedItem());
     try {
         for (Salle salSem : e.editerSalle(idPrestataire)) {
             cmbSemSalle.addItem(String.valueOf(salSem.getNumero()));
         }
     } catch (SQLException ex) {
         Logger.getLogger(FormSeminaire.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_cmbSemPrestaActionPerformed

    private void btSemDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSemDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSemDeleteActionPerformed

    private void btSemUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSemUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSemUpdateActionPerformed

    private void btSemCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSemCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSemCancelActionPerformed

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MousePressed

    private void jLabel16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MousePressed
        new FormMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel16MousePressed

    private void cmbSemSalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSemSalleActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cmbSemSalleActionPerformed

    private void btSemCreatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSemCreatActionPerformed
        int idAnimateur = Integer.parseInt((String)cmbSemAnim.getSelectedItem());
        int idPrestataire = Integer.parseInt((String)cmbSemPresta.getSelectedItem());
        int numSalle = Integer.parseInt((String)cmbSemSalle.getSelectedItem());
        String dureeSem= (String) cmbSemSalle.getSelectedItem();
        Date dateSem=dPickerSeminaire.getDate();
        int nbPlace = Integer.parseInt(txtSemNbPlace.getText());
        double tarifPers = Double.parseDouble(txtSemTarifPers.getText());
        String theme = txtSemThemeSem.getText();
        Seminaire seminaire = new Seminaire(WIDTH, idAnimateur, idPrestataire, numSalle, theme,nbPlace, tarifPers,dureeSem,dateSem);
        CreationSeminaire sem;
     try {
         sem = new CreationSeminaire();
         sem.creerSeminaire(seminaire);
         tabSeminaire.setModel(tab.tableModelSeminaire());
         double [] listeTarif=e.editerTarifPrestataire(idPrestataire);
         double tarifRepas=listeTarif[0];
         double tarifPause=listeTarif[1];
         double depMin=0,depMax=0;
         double beneficeMin=0, beneficeMax=0;
        if(dureeSem.equals("JOURNEE")){
            depMin=(tarifRepas + tarifPause)*(nbPlace/2);
            depMax=(tarifRepas + tarifPause)*(nbPlace);
     
        }else{
            depMin=tarifPause*(nbPlace/2);
            depMax=tarifPause*(nbPlace);            
        }
        beneficeMin=tarifPers*(nbPlace/2);
        beneficeMax=tarifPers*nbPlace;
        lblSemDepenseMin.setText("Depense Min "+depMin);
        lblSemDepenseMax.setText("Depense Max "+depMax);
        lblSemRecetteMin.setText("Recette Min "+beneficeMin);
        lblSemRecetteMax.setText("Recette Max "+beneficeMax);
     } catch (ParseException | SQLException ex) {
         Logger.getLogger(FormSeminaire.class.getName()).log(Level.SEVERE, null, ex);
     }
           
    }//GEN-LAST:event_btSemCreatActionPerformed
    private void setColor(JPanel panel) {
        panel.setBackground(new Color(197, 197, 197));
    }

    private void resetColor(JPanel panel) {
        panel.setBackground(new Color(240, 240, 240));
    }

    private void resetLabelColor(JLabel label) {
        label.setBackground(new Color(45, 118, 232));
    }

    private void setLabelColor(JLabel label) {
        label.setBackground(new Color(197, 197, 197));
    }

    private void resetJPanelColor(JPanel panel) {
        panel.setBackground(new Color(45, 118, 232));
    }

    private void setJPanelColor(JPanel panel) {
        panel.setBackground(new Color(197, 197, 197));
    }

    private void setTextColor(JTextField textField) {
        textField.setBackground(new Color(240, 240, 240));
    }

    private void resetTextColor(JTextField textField) {
        textField.setBackground(new Color(45, 118, 232));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSeminaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSeminaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSeminaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSeminaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormSeminaire().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FormSeminaire.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(FormSeminaire.class.getName()).log(Level.SEVERE, null, ex);
                }
               
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbSemDuréeSem;
    private javax.swing.JButton btSemCancel;
    private javax.swing.JButton btSemCreat;
    private javax.swing.JButton btSemDelete;
    private javax.swing.JButton btSemUpdate;
    private javax.swing.JComboBox<String> cmbSemAnim;
    private javax.swing.JComboBox<String> cmbSemPresta;
    private javax.swing.JComboBox<String> cmbSemSalle;
    private org.jdesktop.swingx.JXDatePicker dPickerSeminaire;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSemDateSem;
    private javax.swing.JLabel lblSemDepenseMax;
    private javax.swing.JLabel lblSemDepenseMin;
    private javax.swing.JLabel lblSemDureeSem;
    private javax.swing.JLabel lblSemIdAnim;
    private javax.swing.JLabel lblSemIdPresta;
    private javax.swing.JLabel lblSemNbPlace;
    private javax.swing.JLabel lblSemNumSalle;
    private javax.swing.JLabel lblSemRecetteMax;
    private javax.swing.JLabel lblSemRecetteMin;
    private javax.swing.JLabel lblSemTarifPers;
    private javax.swing.JLabel lblSemThemeSem;
    private javax.swing.JTable tabSeminaire;
    private javax.swing.JTextField txtSemNbPlace;
    private javax.swing.JTextField txtSemTarifPers;
    private javax.swing.JTextField txtSemThemeSem;
    // End of variables declaration//GEN-END:variables
}
